name: bondy
description: "Datting app"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^14.0.0
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.5+1
  appinio_swiper: ^2.1.1
  http: ^1.2.0
  url_launcher: ^6.3.0
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  dio: ^5.9.2
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^5.1.0
  flutter_markdown_plus: ^1.0.7
  just_audio: ^0.9.46
  record: ^6.0.0
  web_socket_channel: ^3.0.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  confetti: ^0.7.0
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+4
  sentry_flutter: ^8.13.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^4.10.0
  firebase_analytics: ^12.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.20.0
  patrol_finders: ^2.9.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/images/healing_stitch/
    - assets/images/ai_avatars/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
