// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAETXtLziYBD_XLxEt3x8ojr-yKFX87ZRQ',
    appId: '1:228187216169:web:44b38880a94c9860c53f38',
    messagingSenderId: '228187216169',
    projectId: 'bondy-app-d0bb9',
    authDomain: 'bondy-app-d0bb9.firebaseapp.com',
    storageBucket: 'bondy-app-d0bb9.firebasestorage.app',
    measurementId: 'G-XD4HYE0MPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VamK1ZA7advinUMbSV_n71g2EyAG4aM',
    appId: '1:228187216169:android:c2d450e1685e361fc53f38',
    messagingSenderId: '228187216169',
    projectId: 'bondy-app-d0bb9',
    storageBucket: 'bondy-app-d0bb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-J1jZ8wUR7nrxhs5qk2xUy5DvkbB5nY',
    appId: '1:228187216169:ios:f8546d1f68e2f433c53f38',
    messagingSenderId: '228187216169',
    projectId: 'bondy-app-d0bb9',
    storageBucket: 'bondy-app-d0bb9.firebasestorage.app',
    iosBundleId: 'com.exe.bondyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf-J1jZ8wUR7nrxhs5qk2xUy5DvkbB5nY',
    appId: '1:228187216169:ios:f8546d1f68e2f433c53f38',
    messagingSenderId: '228187216169',
    projectId: 'bondy-app-d0bb9',
    storageBucket: 'bondy-app-d0bb9.firebasestorage.app',
    iosBundleId: 'com.exe.bondyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAETXtLziYBD_XLxEt3x8ojr-yKFX87ZRQ',
    appId: '1:228187216169:web:6234521fe4c5f775c53f38',
    messagingSenderId: '228187216169',
    projectId: 'bondy-app-d0bb9',
    authDomain: 'bondy-app-d0bb9.firebaseapp.com',
    storageBucket: 'bondy-app-d0bb9.firebasestorage.app',
    measurementId: 'G-HKXWLTNDK9',
  );
}
